<a href="https://colab.research.google.com/github/GeerbaniShashi/Sololearn_Machine_Learning/blob/main/Model_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values
model = LogisticRegression()
model.fit(X, y)
y_pred = model.predict(X)

print("accuracy:", accuracy_score(y, y_pred))
print("precision:", precision_score(y, y_pred))
print("recall:", recall_score(y, y_pred))
print("f1 score:", f1_score(y, y_pred))

accuracy: 0.8049605411499436
precision: 0.7734627831715211
recall: 0.6988304093567251
f1 score: 0.7342549923195084


In [2]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values
model = LogisticRegression()
model.fit(X, y)
y_pred = model.predict(X)

print("confusion matrix:", confusion_matrix(y, y_pred))

confusion matrix: [[475  70]
 [103 239]]


In [3]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values

X_train, X_test, y_train, y_test = train_test_split(X, y)

print("whole dataset:", X.shape, y.shape)
print("training set:", X_train.shape, y_train.shape)
print("test set:", X_test.shape, y_test.shape)

whole dataset: (887, 6) (887,)
training set: (665, 6) (665,)
test set: (222, 6) (222,)


In [4]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values

X_train, X_test, y_train, y_test = train_test_split(X, y)

#Building the model
model = LogisticRegression()
model.fit(X_train, y_train)

#evaluating the model
#print("accuracy score:", model.score(X_test, y_test))

y_pred = model.predict(X_test)
print("accuracy:", accuracy_score(y_test, y_pred))
print("precision:", precision_score(y_test, y_pred))
print("recall:", recall_score(y_test, y_pred))
print("f1 score:", f1_score(y_test, y_pred))

accuracy: 0.8333333333333334
precision: 0.8
recall: 0.7727272727272727
f1 score: 0.7861271676300579


In [5]:
from sklearn.model_selection import train_test_split

X = [[1, 1], [2, 2], [3, 3], [4, 4]]
y = [0, 0, 1, 1]

X_train, X_test, y_train, y_test = train_test_split(X, y)

print("X_train", X_train)
print("X_test", X_test)

X_train [[4, 4], [3, 3], [2, 2]]
X_test [[1, 1]]


In [6]:
from sklearn.metrics import recall_score
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values

X_train, X_test, y_train, y_test = train_test_split(X, y)

#Building the model
model = LogisticRegression()
model.fit(X_train, y_train)

#evaluating the model
#print("accuracy score:", model.score(X_test, y_test))

y_pred = model.predict(X_test)
sensitivity_score = recall_score
print(sensitivity_score(y_test, y_pred))
# 0.6829268292682927

0.6933333333333334


In [7]:
from sklearn.metrics import precision_recall_fscore_support
print(precision_recall_fscore_support(y_test, y_pred))

(array([0.84353741, 0.69333333]), array([0.84353741, 0.69333333]), array([0.84353741, 0.69333333]), array([147,  75]))


In [8]:
def specificity_score(y_true, y_pred):
    p, r, f, s = precision_recall_fscore_support(y_true, y_pred)
    return r[0]
print(specificity_score(y_test, y_pred))

0.8435374149659864


In [9]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, precision_recall_fscore_support

sensitivity_score = recall_score
def sensitivity_Score(y_true, y_pred):
  p, r, f, s = precision_recall_fscore_support(y_true, y_pred)
  return r[0]

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 5)

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("sensitivity:", sensitivity_score(y_test, y_pred))
print("specificity:", specificity_score(y_test, y_pred))

sensitivity: 0.6829268292682927
specificity: 0.9214285714285714


In [10]:
model.predict_proba(X_test)

array([[0.46054198, 0.53945802],
       [0.88810407, 0.11189593],
       [0.13520341, 0.86479659],
       [0.62497211, 0.37502789],
       [0.73723107, 0.26276893],
       [0.85687444, 0.14312556],
       [0.84133507, 0.15866493],
       [0.10656915, 0.89343085],
       [0.12609363, 0.87390637],
       [0.42024788, 0.57975212],
       [0.92436864, 0.07563136],
       [0.83524271, 0.16475729],
       [0.13698687, 0.86301313],
       [0.90217604, 0.09782396],
       [0.60512146, 0.39487854],
       [0.79565169, 0.20434831],
       [0.17515375, 0.82484625],
       [0.4665441 , 0.5334559 ],
       [0.24195961, 0.75804039],
       [0.89248112, 0.10751888],
       [0.28467532, 0.71532468],
       [0.87815025, 0.12184975],
       [0.86200567, 0.13799433],
       [0.87075669, 0.12924331],
       [0.86659248, 0.13340752],
       [0.22589613, 0.77410387],
       [0.85172421, 0.14827579],
       [0.85168033, 0.14831967],
       [0.56230458, 0.43769542],
       [0.6403672 , 0.3596328 ],
       [0.

In [11]:
model.predict_proba(X_test)[:, 1]

array([0.53945802, 0.11189593, 0.86479659, 0.37502789, 0.26276893,
       0.14312556, 0.15866493, 0.89343085, 0.87390637, 0.57975212,
       0.07563136, 0.16475729, 0.86301313, 0.09782396, 0.39487854,
       0.20434831, 0.82484625, 0.5334559 , 0.75804039, 0.10751888,
       0.71532468, 0.12184975, 0.13799433, 0.12924331, 0.13340752,
       0.77410387, 0.14827579, 0.14831967, 0.43769542, 0.3596328 ,
       0.10742891, 0.95011775, 0.48957849, 0.12879052, 0.05238329,
       0.08937177, 0.96349482, 0.4073404 , 0.37260186, 0.04062216,
       0.77274788, 0.09078782, 0.64735019, 0.45822685, 0.55564149,
       0.17828255, 0.25752126, 0.10174742, 0.13816657, 0.73169604,
       0.21943303, 0.15345326, 0.30015846, 0.67303824, 0.14882939,
       0.27755821, 0.92534818, 0.95507432, 0.12605797, 0.66282211,
       0.14821439, 0.85782986, 0.15896965, 0.07670636, 0.14838929,
       0.09033155, 0.03482992, 0.31937002, 0.6269791 , 0.50255333,
       0.3032967 , 0.12850757, 0.92281727, 0.39829837, 0.38463

In [12]:
y_pred = model.predict_proba(X_test)[:, 1] > 0.75

In [13]:
print("precision:", precision_score(y_test, y_pred))
print("recall:", recall_score(y_test, y_pred))

precision: 0.9230769230769231
recall: 0.43902439024390244


In [14]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score
from sklearn.model_selection import train_test_split

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values

X_train, X_test, y_train, y_test = train_test_split(X, y)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict_proba(X_test)[:, 1] > 0.75

print("precision:", precision_score(y_test, y_pred))
print("recall:", recall_score(y_test, y_pred))

precision: 0.925
recall: 0.43529411764705883


In [15]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values

X_train, X_test, y_train, y_test = train_test_split(X, y)

model1 = LogisticRegression()
model1.fit(X_train, y_train)
y_pred_proba1 = model1.predict_proba(X_test)
print("model 1 AUC score:", roc_auc_score(y_test, y_pred_proba1[:, 1]))

model2 = LogisticRegression()
model2.fit(X_train[:, 0:2], y_train)
y_pred_proba2 = model2.predict_proba(X_test[:, 0:2])
print("model 2 AUC score:", roc_auc_score(y_test, y_pred_proba1[:, 1]))

model 1 AUC score: 0.8472967220093657
model 2 AUC score: 0.8472967220093657


In [16]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
import numpy as np

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values

X_train, X_test, y_train, y_test = train_test_split(X, y)

#building the model
model = LogisticRegression()
model.fit(X_train, y_train)

#evaluating the model
y_pred = model.predict(X_test)
print("  accuracy: {0:.5f}".format(accuracy_score(y_test, y_pred)))
print(" precision: {0:.5f}".format(precision_score(y_test, y_pred)))
print("    recall: {0:.5f}".format(recall_score(y_test, y_pred)))
print("  f1 score: {0:.5f}".format(f1_score(y_test, y_pred)))



  accuracy: 0.81532
 precision: 0.72000
    recall: 0.72973
  f1 score: 0.72483


In [17]:
from sklearn.model_selection import KFold
import pandas as pd

df = pd.read_csv('/content/titanic.csv')
X = df[['Age', 'Fare']].values[:6]
y = df['Survived'].values[:6]

kf = KFold(n_splits = 3, shuffle = True)
print(list(kf.split(X)))

[(array([2, 3, 4, 5]), array([0, 1])), (array([0, 1, 3, 5]), array([2, 4])), (array([0, 1, 2, 4]), array([3, 5]))]


In [18]:
from sklearn.model_selection import KFold
import pandas as pd
df = pd.read_csv('/content/titanic.csv')
X = df[['Age', 'Fare']].values[:6]
y = df['Survived'].values[:6]

kf = KFold(n_splits = 3, shuffle = True)

splits = list(kf.split(X))
first_split = splits[0]
train_indices, test_indices = first_split
print("training set indices:", train_indices)
print("test set indices:", test_indices)

X_train = X[train_indices]
X_test = X[test_indices]
y_train = y[train_indices]
y_test = y[test_indices]
print("X_train")
print(X_train)
print("y_train", y_train)
print("X_test")
print(X_test)
print("y_test", y_test)

training set indices: [1 2 3 5]
test set indices: [0 4]
X_train
[[38.     71.2833]
 [26.      7.925 ]
 [35.     53.1   ]
 [27.      8.4583]]
y_train [1 1 1 0]
X_test
[[22.    7.25]
 [35.    8.05]]
y_test [0 0]


In [19]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
import pandas as pd

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values

kf = KFold(n_splits = 5, shuffle = True)

splits = list(kf.split(X))
train_indices, test_indices = splits[0]
X_train = X[train_indices]
X_test = X[test_indices]
y_train = y[train_indices]
y_test = y[test_indices]

model = LogisticRegression()
model.fit(X_train, y_train)
print(model.score(X_test, y_test))

0.7640449438202247


In [20]:
scores = []
kf = KFold(n_splits=5, shuffle=True)
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    model = LogisticRegression()
    model.fit(X_train, y_train)
    scores.append(model.score(X_test, y_test))
print(scores)
# [0.75847, 0.83146, 0.85876, 0.76271, 0.74011]

[0.8314606741573034, 0.7696629213483146, 0.7570621468926554, 0.7853107344632768, 0.8531073446327684]


In [21]:
print(np.mean(scores))
# 0.79029

0.7993207642988637


In [22]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values

scores = []
kf = KFold(n_splits=5, shuffle=True)
for train_index, test_index in kf.split(X):
  X_train, X_test = X[train_index], X[test_index]
  y_train, y_test = y[train_index], y[test_index]
  model = LogisticRegression()
  model.fit(X_train, y_train)
  scores.append(model.score(X_test, y_test))
print(scores)
print(np.mean(scores))
final_model = LogisticRegression()
final_model.fit(X, y)

[0.7584269662921348, 0.797752808988764, 0.8135593220338984, 0.8418079096045198, 0.7853107344632768]
0.7993715482765188


LogisticRegression()

In [23]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
import numpy as np

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'

In [24]:
kf = KFold(n_splits=5, shuffle=True)

In [25]:
X1 = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
X2 = df[['Pclass', 'male', 'Age']].values
X3 = df[['Fare', 'Age']].values
y = df['Survived'].values

In [27]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
import numpy as np

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'

kf = KFold(n_splits = 5, shuffle = True)

X1 = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
X2 = df[['Pclass', 'male','Age']].values
X3 = df[['Fare', 'Age']].values
y = df['Survived'].values

def score_model(X, y, kf):
  accuracy_scores = []
  precision_scores = []
  recall_scores = []
  f1_scores = []
  for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    model = LogisticRegression()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy_scores.append(accuracy_score(y_test, y_pred))
    precision_scores.append(precision_score(y_test, y_pred))
    recall_scores.append(recall_score(y_test, y_pred))
    f1_scores.append(f1_score(y_test, y_pred))
  print("accuracy:", np.mean(accuracy_scores))
  print("precision:", np.mean(precision_scores))
  print("recall:", np.mean(recall_scores))
  print("f1 score:", np.mean(f1_scores))

print("Logistic Regression with all features")
score_model(X1, y, kf)
print("Logistic Regression with Pclass, Sex & Age features")
score_model(X2, y, kf)
print("Logistic Regression with Fare & Age features")
score_model(X3, y, kf)

Logistic Regression with all features
accuracy: 0.794820034279185
precision: 0.7518494794323829
recall: 0.6948172604422604
f1 score: 0.7218531076546589
Logistic Regression with Pclass, Sex & Age features
accuracy: 0.7947692503015299
precision: 0.7486823830095479
recall: 0.7058986512366594
f1 score: 0.725135688298636
Logistic Regression with Fare & Age features
accuracy: 0.6493683742779153
precision: 0.6282403736614263
recall: 0.22571277159512454
f1 score: 0.3294301949237096


In [28]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
import numpy as np

df = pd.read_csv('/content/titanic.csv')
df['male'] = df['Sex'] == 'male'

kf = KFold(n_splits = 5, shuffle = True)

X1 = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
X2 = df[['Pclass', 'male','Age']].values
X3 = df[['Fare', 'Age']].values
y = df['Survived'].values

def score_model(X, y, kf):
  accuracy_scores = []
  precision_scores = []
  recall_scores = []
  f1_scores = []
  for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    model = LogisticRegression()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy_scores.append(accuracy_score(y_test, y_pred))
    precision_scores.append(precision_score(y_test, y_pred))
    recall_scores.append(recall_score(y_test, y_pred))
    f1_scores.append(f1_score(y_test, y_pred))
  print("accuracy:", np.mean(accuracy_scores))
  print("precision:", np.mean(precision_scores))
  print("recall:", np.mean(recall_scores))
  print("f1 score:", np.mean(f1_scores))

print("Logistic Regression with all features")
score_model(X1, y, kf)
print("Logistic Regression with Pclass, Sex & Age features")
score_model(X2, y, kf)
print("Logistic Regression with Fare & Age features")
score_model(X3, y, kf)

model = LogisticRegression()
model.fit(X_train, y_train)

print(model.predict([[3, False, 25, 0, 1, 2]]))

Logistic Regression with all features
accuracy: 0.8027169428045451
precision: 0.7613646084490966
recall: 0.6983510744627687
f1 score: 0.7275016914158293
Logistic Regression with Pclass, Sex & Age features
accuracy: 0.7948136862819781
precision: 0.7531069659216113
recall: 0.7002507459285627
f1 score: 0.7243232694991294
Logistic Regression with Fare & Age features
accuracy: 0.6539579762584904
precision: 0.6406358328772123
recall: 0.23589947812574455
f1 score: 0.3426647493976721
[1]


**Machine Learning - Welcome to the Matrix**

Calculating Evaluation Metrics using the Confusion Matrix.

**Task**

You will be given the values of the confusion matrix (true positives, false positives, false negatives, and true negatives). Your job is to compute the accuracy, precision, recall and f1 score and print the values rounded to 4 decimal places. To round, you can use round(x, 4).

**Input Format**

The values of tp, fp, fn, tn, in that order separated by spaces

**Output Format**

Each value on its own line, rounded to 4 decimal places, in this order:
accuracy, precision, recall, f1 score

**Sample Input**

233 65 109 480

**Sample Output**

0.8038
0.7819
0.6813
0.7281

**Explanation**

Accuracy is (tp + tn) / total = (233+480)/(233+65+109+480)=0.8038
Precision is tp / (tp + fp) = 233/(233+65) = 0.7819
Recall is tp / (tp + fn) = 233/(233+109) = 0.6813
F1 score is 2 * precision * recall / (precision + recall) = 2*0.7819*0.6813/(0.7819+0.6813) = 0.7281

In [31]:
tp, fp, fn, tn = [int(x) for x in input().split()]
accuracy = (tp + tn) / (tp + fp + fn + tn)
precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1_score = 2 * precision * recall / (precision + recall)
print(round(accuracy, 4))
print(round(precision, 4))
print(round(recall, 4))
print(round(f1_score, 4))

233 65 109 480
0.8038
0.7819
0.6813
0.7281
